server:
  port: 8090

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8280/realms/banking-realm

app:
  config:
    keycloak:
      server-url: http://localhost:8280
      realm: banking-realm
      client-id: user-service
      client-secret: z5yklGXHMwS7ZJy9ZniGTGKG1HFp4ImV

  codes:
    bad_request: 400
    conflict: 409
    success: 200
    not_found: 404		
  email:
   verification:
        enabled: true
        resend-limit: 3
        expiry-hourse: 1
      
